version: '3'

services:
  postgres:
    image: postgres
    container_name: arcode-postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - arcode-network
  
  arcode-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arcode-api
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/arcode/
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - arcode-network
      
volumes:
  postgres-db:

networks:
  arcode-network: